import Head from "next/head";
import CarouselHeader from "../components/CarouselHeader";
import Navbar from "../components/Navbar";
import About from "../components/About";
import VisiMisi from "../components/VisiMisi";
import Team from "../components/Team";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Youngtalk Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl mx-auto">
        <Navbar />
        {/* <CarouselHeader />  */}
        <About />
        <VisiMisi />
        {/* 
        <Team />
        <Footer /> */}
      </main>
    </div>
  );
}
